#!/usr/bin/env python3
"""
Per-coder coding order, and the test-retest draw.

    python audit/order.py --coder R1
    python audit/order.py --coder R2 --retest

Why not just work down frame.csv: if both coders take the documents in the same
order they are equally fresh on document 1 and equally tired on document 48, so
their calibration drift correlates and inter-coder agreement comes out higher
than it should. Independent orders decorrelate the drift.

The order is derived from the coder's LABEL plus a fixed seed, so it is
reproducible and can be regenerated if a sheet is lost, but is not something the
coder chose. The labels are roles, not initials: R1 and R2 are rater 1 and
rater 2, and they are symmetric because the coders are -- both are external to
the design team and neither designed the taxonomy (CODEBOOK.md section 6). R
rather than C so that coder labels do not collide with the stratum C document
identifiers C01-C26. Keeping them identity-free is what lets a third party
regenerate either order without being told who coded what.

--retest prints the five documents to re-code at the very end, blind to the
earlier codes, for intra-coder agreement.
"""

from __future__ import annotations

import argparse
import csv
import random
from pathlib import Path

SEED = 20260812
HERE = Path(__file__).resolve().parent
# The nine calibration-pilot documents (CODEBOOK.md section 5.2), generated by
# the stated rule: the lowest-numbered document from each of the first three
# organisations in each census stratum, plus the first three stratum-B
# documents. Three genres, six of the seven organisations. Kept identical to
# PILOT in score.py -- score.py --selftest asserts the two lists match, because
# if they drift the primary kappa is computed over a different set than the
# manual says it is.
PILOT = ["A01", "A10", "A14", "B01", "B02", "B03", "C01", "C16", "C22"]


# The v1.5 frame reduction (per-organisation cap 5 -> 3) removes documents from
# the draw. Each coder's order must survive that by DELETION, never by
# re-permutation: re-running the sample over 41 documents yields a different
# order, and both the annex and START-HERE tell coders their order does not
# change. So the permutation is still taken over the registered draw -- the 50
# as drawn, capped_v15 rows included -- and the removed documents are dropped
# from the result afterwards. Survivors keep their relative positions exactly.
REGISTERED_DRAW = ("draw", "capped_v15")


def load(frame: Path) -> list[dict]:
    """The registered draw, for permutation. Includes rows later capped out."""
    with frame.open(encoding="utf-8") as fh:
        return [r for r in csv.DictReader(fh) if r["status"] in REGISTERED_DRAW]


def still_in_frame(r: dict) -> bool:
    return r["status"] == "draw"


def coder_seed(initials: str) -> int:
    # Deterministic across machines and Python versions: hash() is salted, so it
    # would give a different order on every run.
    return SEED + sum(ord(c) for c in initials.upper())


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--coder", required=True, choices=["R1", "R2"],
                    help="coder label: R1 or R2 (CODEBOOK.md section 6)")
    ap.add_argument("--frame", default=str(HERE / "frame.csv"))
    ap.add_argument("--retest", action="store_true",
                    help="print the 5 test-retest documents instead")
    ap.add_argument("--pilot", action="store_true",
                    help="print the shared pilot set instead")
    ap.add_argument("--markdown", action="store_true",
                    help="emit a tick-list with links, for use as a worklist")
    a = ap.parse_args()

    rows = load(Path(a.frame))
    by_id = {r["id"]: r for r in rows}
    rng = random.Random(coder_seed(a.coder))

    if a.pilot:
        print(f"# Pilot set — the SAME {len(PILOT)} documents for both coders (codebook 5.2)")
        print(f"# These are EXCLUDED from the primary kappa: you will discuss every")
        print(f"# disagreement on them, so agreement here measures the discussion.")
        for i, d in enumerate(PILOT, 1):
            r = by_id[d]
            print(f"{i:>3}. {d}  {r['title'][:60]}")
            print(f"      {r['url']}")
        return 0

    main_pass = [r for r in rows if r["id"] not in PILOT]
    order = rng.sample(main_pass, len(main_pass))
    # delete, do not re-permute
    order = [r for r in order if still_in_frame(r)]

    if a.retest:
        # Drawn from what this coder actually coded, late enough in their own
        # order that the earlier codes are not fresh in memory.
        pool = order[: int(len(order) * 0.6)]
        picks = random.Random(coder_seed(a.coder) + 977).sample(pool, 5)
        print(f"# Test-retest for {a.coder.upper()} — re-code these 5 LAST, without")
        print(f"# looking at your earlier sheet. Save as codes-{a.coder.upper()}-retest.csv")
        for i, r in enumerate(picks, 1):
            print(f"{i:>3}. {r['id']}  {r['title'][:60]}")
            print(f"      {r['url']}")
        return 0

    if a.markdown:
        print(f"# Worklist — {a.coder.upper()}\n")
        print(f"{len(order)} documents, in your own order. Do the shared pilot first")
        print(f"(`python audit/order.py --coder {a.coder.upper()} --pilot`).\n")
        print("Tick each when its row is filled in. Roughly 8-12 minutes each.\n")
        for i, r in enumerate(order, 1):
            print(f"- [ ] **{r['id']}** — [{r['title']}]({r['url']})")
        print(f"\nWhen all are ticked, run the test-retest:")
        print(f"`python audit/order.py --coder {a.coder.upper()} --retest`")
        return 0

    print(f"# Coding order for {a.coder.upper()} — {len(order)} documents")
    print(f"# Work top to bottom. Do the pilot first (--pilot).")
    for i, r in enumerate(order, 1):
        print(f"{i:>3}. {r['id']:<5} {r['stratum']:<14} {r['title'][:58]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
